"""Build the meeting-insights HTML email from a stored report.

Empty sections render as a neutral "None noted" rather than being faked or
hidden silently — the reader can tell the difference between "nothing" and "not
captured". Inline styles only (email clients strip <style>).
"""
from __future__ import annotations

import html as _html

from app.db.models import Meeting, MeetingReport

_WRAP = (
    "font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;"
    "max-width:640px;margin:0 auto;color:#1a1a1a;line-height:1.5;"
)
_H = "font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:.04em;color:#6b7280;margin:24px 0 8px;"
_LI = "margin:4px 0;"


def _esc(value: object) -> str:
    return _html.escape(str(value)) if value is not None else ""


def build_subject(meeting: Meeting) -> str:
    title = meeting.title or "Meeting"
    return f"Meeting Insights — {title}"


def _bullets(items: list | None) -> str:
    if not items:
        return '<p style="margin:4px 0;color:#9ca3af;">None noted.</p>'
    lis = "".join(f'<li style="{_LI}">{_esc(i)}</li>' for i in items)
    return f'<ul style="margin:4px 0 0;padding-left:20px;">{lis}</ul>'


def _action_items(items: list | None) -> str:
    if not items:
        return '<p style="margin:4px 0;color:#9ca3af;">None noted.</p>'
    rows = []
    for it in items:
        if not isinstance(it, dict):
            rows.append(f'<li style="{_LI}">{_esc(it)}</li>')
            continue
        owner = it.get("owner")
        task = it.get("task", "")
        if owner:
            rows.append(f'<li style="{_LI}"><strong>{_esc(owner)}</strong> — {_esc(task)}</li>')
        else:
            rows.append(f'<li style="{_LI}">{_esc(task)}</li>')
    return f'<ul style="margin:4px 0 0;padding-left:20px;">{"".join(rows)}</ul>'


def build_html(meeting: Meeting, report: MeetingReport) -> str:
    title = _esc(meeting.title or "Meeting")
    summary = _esc(report.summary) if report.summary else "No summary available."
    when = _esc(meeting.start_time.isoformat()) if meeting.start_time else ""

    return f"""\
<div style="{_WRAP}">
  <div style="border-bottom:2px solid #111;padding-bottom:12px;margin-bottom:8px;">
    <div style="font-size:12px;color:#6b7280;">CentralAgent · Meeting Insights</div>
    <h1 style="font-size:22px;margin:6px 0 0;">{title}</h1>
    {f'<div style="font-size:13px;color:#6b7280;margin-top:4px;">{when}</div>' if when else ''}
  </div>

  <div style="{_H}">Summary</div>
  <p style="margin:4px 0;">{summary}</p>

  <div style="{_H}">Key Decisions</div>
  {_bullets(report.decisions)}

  <div style="{_H}">Action Items</div>
  {_action_items(report.action_items)}

  <div style="{_H}">Risks</div>
  {_bullets(report.risks)}

  <div style="{_H}">Next Steps</div>
  {_bullets(report.next_steps)}

  <div style="margin-top:28px;padding-top:12px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af;">
    Generated by CentralAgent from the meeting transcript. "None noted" means the item
    was not found in the transcript.
  </div>
</div>"""
