"""SQLAlchemy models — meetings, transcripts, and generated reports.

State machine (see HLD):
    PENDING -> SCHEDULED -> JOINING -> ACTIVE -> PROCESSING -> COMPLETED
Failure branches: CANCELLED, FAILED_JOIN, FAILED_RECORDING, FAILED_ANALYSIS,
EMAIL_FAILED.
"""
from __future__ import annotations

import enum
from datetime import datetime

from sqlalchemy import (
    BigInteger,
    DateTime,
    Enum as SAEnum,
    ForeignKey,
    Index,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin


class MeetingStatus(str, enum.Enum):
    """Lifecycle of a single meeting the bot handles."""

    PENDING = "pending"            # detected, not yet scheduled
    SCHEDULED = "scheduled"        # waiting for start time to dispatch the bot
    JOINING = "joining"            # bot dispatched, joining/awaiting admission
    ACTIVE = "active"              # bot in the meeting, recording
    PROCESSING = "processing"      # meeting ended, transcript -> insights in flight
    COMPLETED = "completed"        # insights emailed, done
    # Failure branches
    CANCELLED = "cancelled"
    FAILED_JOIN = "failed_join"
    FAILED_RECORDING = "failed_recording"
    FAILED_ANALYSIS = "failed_analysis"
    EMAIL_FAILED = "email_failed"


# Statuses from which the scheduler may still dispatch / act.
ACTIVE_STATUSES = {
    MeetingStatus.PENDING,
    MeetingStatus.SCHEDULED,
    MeetingStatus.JOINING,
    MeetingStatus.ACTIVE,
    MeetingStatus.PROCESSING,
}


class Meeting(Base, TimestampMixin):
    """A meeting the bot is (or was) responsible for joining."""

    __tablename__ = "meetings"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)

    # Idempotency key from Google Calendar (null for manually dispatched meetings).
    google_event_id: Mapped[str | None] = mapped_column(String(256), unique=True, index=True)

    platform: Mapped[str] = mapped_column(String(32), default="google_meet", nullable=False)
    # The "abc-defg-hij" portion of the Meet URL (Vexa's native_meeting_id).
    native_meeting_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    meet_url: Mapped[str] = mapped_column(String(512), nullable=False)

    title: Mapped[str | None] = mapped_column(String(512))
    organizer_email: Mapped[str | None] = mapped_column(String(320), index=True)

    start_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)
    end_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    status: Mapped[MeetingStatus] = mapped_column(
        SAEnum(MeetingStatus, name="meeting_status", native_enum=False, length=32),
        default=MeetingStatus.PENDING,
        nullable=False,
        index=True,
    )

    # Vexa's internal meeting/bot id (from POST /bots response).
    vexa_bot_id: Mapped[str | None] = mapped_column(String(64))

    # Scheduler bookkeeping (claim-locking so two workers never double-dispatch).
    dispatch_claimed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    bot_dispatched_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    failure_reason: Mapped[str | None] = mapped_column(Text)

    transcript: Mapped["Transcript | None"] = relationship(
        back_populates="meeting", cascade="all, delete-orphan", uselist=False
    )
    report: Mapped["MeetingReport | None"] = relationship(
        back_populates="meeting", cascade="all, delete-orphan", uselist=False
    )

    __table_args__ = (
        Index("ix_meetings_status_start", "status", "start_time"),
    )


class Transcript(Base, TimestampMixin):
    """Raw transcript captured from Vexa — preserved before Gemini analysis."""

    __tablename__ = "transcripts"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    meeting_id: Mapped[int] = mapped_column(
        ForeignKey("meetings.id", ondelete="CASCADE"), unique=True, nullable=False, index=True
    )

    # List of {speaker, text, start, end, ...} segments as returned by Vexa.
    segments: Mapped[list | None] = mapped_column(JSONB)
    full_text: Mapped[str | None] = mapped_column(Text)
    source: Mapped[str] = mapped_column(String(32), default="vexa_cloud", nullable=False)
    fetched_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    meeting: Mapped[Meeting] = relationship(back_populates="transcript")


class MeetingReport(Base, TimestampMixin):
    """Structured insights generated by Gemini from the transcript."""

    __tablename__ = "meeting_reports"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    meeting_id: Mapped[int] = mapped_column(
        ForeignKey("meetings.id", ondelete="CASCADE"), unique=True, nullable=False, index=True
    )

    summary: Mapped[str | None] = mapped_column(Text)
    decisions: Mapped[list | None] = mapped_column(JSONB)
    action_items: Mapped[list | None] = mapped_column(JSONB)
    risks: Mapped[list | None] = mapped_column(JSONB)
    next_steps: Mapped[list | None] = mapped_column(JSONB)

    model_used: Mapped[str | None] = mapped_column(String(64))
    email_sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    meeting: Mapped[Meeting] = relationship(back_populates="report")
