"""initial schema: meetings, transcripts, reports

Revision ID: baf0f4995237
Revises: 
Create Date: 2026-06-10 20:03:36.867606+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baf0f4995237'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('google_event_id', sa.String(length=256), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('native_meeting_id', sa.String(length=64), nullable=False),
    sa.Column('meet_url', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('organizer_email', sa.String(length=320), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'JOINING', 'ACTIVE', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'FAILED_JOIN', 'FAILED_RECORDING', 'FAILED_ANALYSIS', 'EMAIL_FAILED', name='meeting_status', native_enum=False, length=32), nullable=False),
    sa.Column('vexa_bot_id', sa.String(length=64), nullable=True),
    sa.Column('dispatch_claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bot_dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_google_event_id'), 'meetings', ['google_event_id'], unique=True)
    op.create_index(op.f('ix_meetings_native_meeting_id'), 'meetings', ['native_meeting_id'], unique=False)
    op.create_index(op.f('ix_meetings_organizer_email'), 'meetings', ['organizer_email'], unique=False)
    op.create_index(op.f('ix_meetings_start_time'), 'meetings', ['start_time'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index('ix_meetings_status_start', 'meetings', ['status', 'start_time'], unique=False)
    op.create_table('meeting_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_reports_meeting_id'), 'meeting_reports', ['meeting_id'], unique=True)
    op.create_table('transcripts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_meeting_id'), 'transcripts', ['meeting_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_meeting_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_meeting_reports_meeting_id'), table_name='meeting_reports')
    op.drop_table('meeting_reports')
    op.drop_index('ix_meetings_status_start', table_name='meetings')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_start_time'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_organizer_email'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_native_meeting_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_google_event_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
